### ISSUE TITLE
Cannot include multiple protoPaths

### ISSUE THREAD

**Issue by pathammer** [hronro/webpack-grpc-web-loader#3]
protoc supports including multiple paths for search for proto files in. I can't figure out how to get this loader to take the same options.

From `protoc --help`

`Specify the directory in which to search for
                              imports.  May be specified multiple times;
                              directories will be searched in order.  If not
                              given, the current working directory is used.
                              If not found in any of the these directories,
                              the --descriptor_set_in descriptors will be
                              checked for required proto file.`

**Comment by hronro** [comment]
I haven't use multi path before. Do you mean the protoc can accept options like this:

```
protoc -I /my-dir/path1 -I /my-dir/path2
```

**Comment by pathammer** [comment]
Yes exactly. That PR looks good. I'll test it out for my use case tomorrow thanks!

**Comment by hronro** [comment]
I just published `webpack-grpc-web-loader@0.1.5`, you can try that.

Feel free to reopen the issue if you meet any problems.

**Comment by pathammer** [comment]
Unfortunately this doesn't fix the problem 100%
Part of the point of including multiple proto paths is so you can include proto files inside each other. For example, you might want to `import "google/protobuf/empty.proto";`
that file is provided by the `libprotobuf-dev` ubuntu package and found in `/usr/include/google/protobuf/empty.proto`
The problem is that the generated js calls 
```
var google_protobuf_empty_pb = require(google-protobuf/google/protobuf/empty_pb.js)
```
and since this webpack plugin puts all the generated code in different temp dirs, none of the `require` calls resolve the correct files.

Any idea how to solve this? I would suggest using this simple proto definition to test the include functionality.

```
syntax = "proto3";

package action;

import "google/protobuf/empty.proto";

service ActionInterface {
  rpc Execute (google.protobuf.Empty) returns (google.protobuf.Empty);
}
```

**Comment by hronro** [comment]
I'll do some research and reply this later.

**Comment by fidabhittani** [comment]
Are you still researching?

**Comment by hronro** [comment]
@pathammer @fidabhittani 

Sorry for the delay, I was really busy in the last couple of months.

I just have a peek of this issue, I found it can be simply fixed by `npm install google-protobuf`.

Can you help check if it works?

**Comment by pathammer** [comment]
Yes google-protobuf fixes the missing empty.js dependency but there are other issues.

Imagine you wanted to compile [viewport.proto from google-api](https://github.com/googleapis/googleapis/blob/master/google/geo/type/viewport.proto). You would add the root directory of the repository as the proto-path so that the namespaces are resolved correctly.

The [generatedFileName](https://github.com/foisonocean/webpack-grpc-web-loader/blob/0a85d300d44eee309e05609bc71f757d6c1a1e3e/index.js#L69) does not account for namespace and so webpack can't find the generated file.

It would be a good test to get this plugin to load a complex grpc project like something from googleapis
